export const SET_SELECTED_SHAPE_ID = "SET_SELECTED_SHAPE_ID";
export const UPDATE_SELECTED_SHAPE_ID = "UPDATE_SELECTED_SHAPE_ID";
export const UPDATE_SHAPE = "UPDATE_SHAPE";
export const ADD_SHAPE = "ADD_SHAPE";
export const DELETE_SHAPE = "DELETE_SHAPE";
export const DISABLE_HOVER = "DISABLE_HOVER";
