export const SHAPES = {
  ELLIPSE: "ELLIPSE",
  RECTANGLE: "RECTANGLE",
  LINE: "LINE",
  ARROW: "ARROW",
  POLYGON: "POLYGON",
  STAR: "STAR",
  IMAGE: "IMAGE",
  TEXT: "TEXT",
};

export const SHAPES_CONFIG = {
  ELLIPSE: {
    x: 80,
    y: 150,
    width: 100,
    height: 100,
    fill: "gray",
    display: true,
  },
  RECTANGLE: {
    x: 50,
    y: 100,
    width: 100,
    height: 100,
    fill: "gray",
    display: true,
  },
  LINE: {
    x: 50,
    stroke: "gray",
    strokeWidth: 5,
    y: 100,
    points: [0, 100, 100, 0],
    display: true,
  },
  ARROW: {
    x: 50,
    stroke: "gray",
    strokeWidth: 5,
    y: 100,
    points: [0, 100, 100, 0],
    display: true,
  },
  POLYGON: {
    x: 100,
    stroke: "gray",
    strokeWidth: 5,
    y: 200,
    sides: 3,
    radius: 70,
    display: true,
  },
  STAR: {
    x: 100,
    y: 150,
    numPoints: 5,
    innerRadius: 40,
    outerRadius: 70,
    fill: "gray",
    stroke: "black",
    strokeWidth: 4,
    display: true,
  },
  IMAGE: {
    display: true,
  },
  TEXT: {
    display: true,
    text: "Text",
    fontFamily: "Times New Roman",
    fontSize: 24,
    x: 100,
    y: 100,
  },
};
